<h1 style=" text-align: center;">Members Management</h1>

  <?php if (isset($_GET['success'])): ?>
    <div id="message" class="alert alert-success" role="alert">
      Member added successfully!
    </div>
  <?php endif ?>

  <?php if (isset($_GET['danger'])): ?>
    <div id="message" class="alert alert-danger" role="alert">
      Member deleted successfully!
    </div>
  <?php endif ?>

  <?php if (isset($_GET['success_all'])): ?>
    <div id="message" class="alert alert-success" role="alert">
      All books have been deleted successfully!
    </div>
  <?php endif ?>

  <?php if (isset($_GET['error_all'])): ?>
    <div id="message" class="alert alert-danger" role="alert">
      There was an error deleting the books.
    </div>
  <?php endif ?>

  

  <div class="d-flex justify-content-between align-items-center mb-4">
      <h2 class="text-dark"><i class="bi bi-card-list"></i> List of Members</h2>
      <a class="btn btn-primary" href="add_member.php" role="button"><i class="bi bi-person-add"> Add Member</i></a>
  </div>

  <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Full Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Date of registration</th>
      <th >Options</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($mbrs as $mbr): ?>
      <tr>
        <th scope="row"><?=$mbr['id']?></th>
        <td><?=$mbr['full_name']?></td>
        <td><?=$mbr['email']?></td>
        <td><?=$mbr['telephone']?></td>
        <td><?=$mbr['date_inscription']?></td>
        <td>
          <a class="btn btn-primary" href="member_info.php? id=<?=$mbr['id']?>" role="button"><i class="bi bi-info-square"></i></a>

          <a class="btn btn-success" href="edit_member.php? id=<?=$mbr['id']?>" role="button"><i class="bi bi-pencil-square"></i></a>
    
          <!-- Trigger Modal -->
          <a class="btn btn-danger" role="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop<?=$mbr['id']?>"><i class="bi bi-trash"></i></a>
          
          <!-- Modal for each book -->
          <div class="modal fade" id="staticBackdrop<?=$mbr['id']?>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel<?=$mbr['id']?>" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="staticBackdropLabel<?=$mbr['id']?>">Delete <?=$mbr['full_name']?></h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  Are you sure you want to delete this member?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                  <button type="button" class="btn btn-primary">
                    <a class="btn btn-primary" href="delete_member.php? id=<?=$mbr['id']?>" role="button">Yes</a>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>
